def adapt_from_trunk(fixture_obj, stats, ctx):
    return {
        'case_id': ctx['case_id'],
        'fixture_id': fixture_obj['fixture']['id'],
        'competition': fixture_obj['league']['name'],
        'home_team_name': fixture_obj['teams']['home']['name'],
        'away_team_name': fixture_obj['teams']['away']['name'],
        'home_role': ctx['home_role'],
        'away_role': ctx['away_role'],
        'home': {
            'sample_size': ctx['sample_size'],
            'corners_for_avg': ctx['home_corners_for_avg'],
            'corners_against_avg': ctx['home_corners_against_avg'],
            'corners_for_home_away_avg': max(ctx['home_corners_for_avg'], stats['home_corner_kicks']),
            'corners_against_home_away_avg': ctx['home_corners_against_avg'],
            'total_match_corners_avg': stats['home_corner_kicks'] + stats['away_corner_kicks'],
            'shots_avg': stats['home_total_shots'],
            'final_third_pressure': ctx['home_pressure'],
            'territorial_proxy': stats['home_possession'],
            'hit_rate_over_9_5': ctx['home_hr95'],
            'opponent_adjustment_quality': ctx['home_qa'],
        },
        'away': {
            'sample_size': ctx['sample_size'],
            'corners_for_avg': ctx['away_corners_for_avg'],
            'corners_against_avg': ctx['away_corners_against_avg'],
            'corners_for_home_away_avg': max(ctx['away_corners_for_avg'], stats['away_corner_kicks']),
            'corners_against_home_away_avg': ctx['away_corners_against_avg'],
            'total_match_corners_avg': stats['home_corner_kicks'] + stats['away_corner_kicks'],
            'shots_avg': stats['away_total_shots'],
            'final_third_pressure': ctx['away_pressure'],
            'territorial_proxy': stats['away_possession'],
            'hit_rate_over_9_5': ctx['away_hr95'],
            'opponent_adjustment_quality': ctx['away_qa'],
        },
        'context': {'expected_pace_shape': ctx['pace'], 'expected_game_state_volatility': ctx['vol'], 'likely_rotation': ctx['rotation'], 'low_data_quality': ctx['lowq'], 'unstable_tactical_profile': ctx['unstable']}
    }
