
ALLOWED_TRANSITIONS = {
    'RECEIVED': {'VALIDATION_PENDING'},
    'VALIDATION_PENDING': {'VALIDATED', 'REJECTED_AT_EXECUTION'},
    'VALIDATED': {'READY_TO_EXECUTE'},
    'READY_TO_EXECUTE': {'EXECUTION_PENDING'},
    'EXECUTION_PENDING': {'EXECUTED', 'MISSED', 'CANCELLED', 'MANUAL_REVIEW'},
    'MANUAL_REVIEW': {'READY_TO_EXECUTE', 'MISSED', 'CANCELLED'},
    'EXECUTED': {'AWAITING_SETTLEMENT'},
    'AWAITING_SETTLEMENT': {'SETTLED', 'VOID'},
}
