EXECUTION_STATUSES = [
    "RECEIVED",
    "VALIDATION_PENDING",
    "VALIDATED",
    "REJECTED_AT_EXECUTION",
    "READY_TO_EXECUTE",
    "EXECUTION_PENDING",
    "EXECUTED",
    "MISSED",
    "CANCELLED",
    "MANUAL_REVIEW",
    "AWAITING_SETTLEMENT",
    "VOID",
    "SETTLED",
]

SETTLEMENT_STATUSES = [
    "UNSETTLED",
    "WIN",
    "LOSS",
    "PUSH",
    "HALF_WIN",
    "HALF_LOSS",
    "VOID",
]
